version: '3.3'
services:
#Contenedor mysql para crear la base de datos
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'Aimar'
      MYSQL_USER: 'Aimar'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './datos-reto/mysql/:/var/lib/mysql'
    command: ["--log_bin_trust_function_creators=1"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
# Contenedor de laravel para mantener el servidor
  Server:
          image:  node:latest
          ports:
          - "8083:3000"
          volumes:
            - ../Back/SERVER:/app
          depends_on:
             mysql:
                condition: service_healthy
  API:
          image:  node:latest
          ports:
          - "8086:3000"
          volumes:
            - ../Back/API:/app
          depends_on:
            mysql:
                condition: service_healthy
  #Contenedor con LAMP para guardar nuestra pagina web
  LAMP:
          image: httpd:latest
          ports:
          - "8082:80"
          volumes:
          - ../Front:/usr/local/apache2/htdocs/
  #Contenedor para proxy inversa
  # Inverso:
  #         image: nginx:latest
  #         ports:
  #         - "81:80"
  #         volumes:
  #         - ./inverso/nginx.conf:/etc/nginx/nginx.conf
  #         depends_on:
  #         - LAMP
  #Contenedor phpmyadmin para tener interfaz grafica de la base de datos y comprobar que los datos funcionen
  phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8084:80
        environment:
            - PMA_ARBITRARY=1